(()=>{
'use strict';
const D=document,body=D.body,id=body.dataset.game,canvas=D.querySelector('#game');
if(!canvas)return;
const ctx=canvas.getContext('2d'),W=800,H=600,$=s=>D.querySelector(s),$$=s=>[...D.querySelectorAll(s)];
const ui={score:$('#score'),lives:$('#lives'),level:$('#level'),tickets:$('#tickets'),status:$('#status'),hint:$('#hint'),toast:$('#toast')};
let score=0,lives=3,level=1,tickets=0,running=false,paused=false,ended=false,last=0,keys={},eye=false,dwellTimer=null,game=null,audioCtx=null,musicTimer=null,musicStep=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function hud(){if(ui.score)ui.score.textContent=score;if(ui.lives)ui.lives.textContent=lives;if(ui.level)ui.level.textContent=level;if(ui.tickets)ui.tickets.textContent=tickets;if(ui.status)ui.status.textContent=ended?'Game Over':paused?'Paused':running?'Playing':'Ready'}
function toast(text){if(!ui.toast)return;ui.toast.textContent=text;ui.toast.classList.add('show');clearTimeout(window.__retroToast);window.__retroToast=setTimeout(()=>ui.toast.classList.remove('show'),900)}
function ticket(n){tickets+=n;try{const k='retrocadeState',s=JSON.parse(localStorage.getItem(k)||'{}');s.tickets=(s.tickets||0)+n;s.plays=(s.plays||0)+1;localStorage.setItem(k,JSON.stringify(s))}catch{}toast('+'+n+' tickets');hud()}
function audio(){if(audioCtx)return audioCtx;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;try{audioCtx=new AC()}catch{return null}return audioCtx}
function unlockAudio(){const a=audio();if(a&&a.state==='suspended')a.resume().catch(()=>{})}
function tone(f=440,d=.08,type='sine',v=.045,delay=0){const a=audio();if(!a)return;try{const o=a.createOscillator(),g=a.createGain(),t=a.currentTime+delay;o.type=type;o.frequency.setValueAtTime(f,t);o.connect(g);g.connect(a.destination);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.start(t);o.stop(t+d+.02)}catch{}}
const themes={asteroids:[110,165,220,330],claw:[196,247,294,392],bubble:[262,330,392,523],racer:[82,123,165,247],rhythm:[220,294,392,523],blocks:[98,147,196,294]};
function startMusic(){if(musicTimer||!running||paused)return;const seq=themes[id]||themes.asteroids;musicTimer=setInterval(()=>{if(!running||paused)return;const f=seq[musicStep++%seq.length];tone(f,.12,'triangle',.018)},430)}
function stopMusic(){clearInterval(musicTimer);musicTimer=null}
function begin(){unlockAudio();if(ended)reset();running=true;paused=false;ui.hint?.classList.add('hide');startMusic();hud()}
function loseLife(){if(ended)return;lives--;tone(92,.24,'sawtooth',.07);if(lives<=0){ended=true;running=false;paused=false;stopMusic();ticket(Math.max(2,Math.floor(score/100)));toast('Game over');}else game.respawn?.();hud()}
function rr(x,y,w,h,r,c){ctx.fillStyle=c;ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h);ctx.fill()}
function bg(c1='#0b1830',c2='#050b16'){const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,c1);g.addColorStop(1,c2);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(255,255,255,.035)';for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function asteroids(){let ship,rocks,shots,cool,inv;const spawn=()=>rocks=Array.from({length:5+level},()=>({x:rand(40,760),y:rand(40,560),vx:rand(-1.7,1.7),vy:rand(-1.7,1.7),r:rand(18,40)}));return{reset(){ship={x:400,y:330,a:-Math.PI/2,vx:0,vy:0};shots=[];cool=0;inv=.8;spawn()},respawn(){ship.x=400;ship.y=330;ship.vx=ship.vy=0;inv=1},action(){begin();if(cool<=0){shots.push({x:ship.x,y:ship.y,vx:Math.cos(ship.a)*9,vy:Math.sin(ship.a)*9,life:75});cool=.17;tone(560,.055,'square',.05)}},move(d){begin();if(d==='left')ship.a-=.22;if(d==='right')ship.a+=.22;if(d==='up'){ship.vx+=Math.cos(ship.a)*.8;ship.vy+=Math.sin(ship.a)*.8}},pointer(x,y,type){if(type!=='down')return;begin();ship.a=Math.atan2(y-ship.y,x-ship.x);this.action()},update(dt){cool-=dt;inv=Math.max(0,inv-dt);if(keys.left)ship.a-=.055;if(keys.right)ship.a+=.055;if(keys.up){ship.vx+=Math.cos(ship.a)*.16;ship.vy+=Math.sin(ship.a)*.16}ship.x=(ship.x+ship.vx+W)%W;ship.y=(ship.y+ship.vy+H)%H;ship.vx*=.99;ship.vy*=.99;shots.forEach(s=>{s.x=(s.x+s.vx+W)%W;s.y=(s.y+s.vy+H)%H;s.life--});shots=shots.filter(s=>s.life>0);rocks.forEach(r=>{r.x=(r.x+r.vx+W)%W;r.y=(r.y+r.vy+H)%H});rocks=rocks.filter(r=>{const s=shots.find(q=>Math.hypot(q.x-r.x,q.y-r.y)<r.r);if(!s)return true;s.life=0;score+=15;tone(180+Math.min(score,500),.07,'triangle');hud();return false});if(inv<=0&&rocks.some(r=>Math.hypot(ship.x-r.x,ship.y-r.y)<r.r+14)){inv=1;loseLife()}if(!rocks.length){level++;ticket(12);spawn();hud()}},draw(){bg('#07152a','#030914');rocks.forEach(r=>{ctx.strokeStyle='#9a87ff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke()});shots.forEach(s=>rr(s.x,s.y,6,6,3,'#ffe17b'));ctx.save();ctx.globalAlpha=inv>0&&Math.floor(inv*10)%2?0.35:1;ctx.translate(ship.x,ship.y);ctx.rotate(ship.a+Math.PI/2);ctx.fillStyle='#59e2ff';ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(16,18);ctx.lineTo(0,10);ctx.lineTo(-16,18);ctx.closePath();ctx.fill();ctx.restore()}}}
function claw(){let x,y,mode,prizes,held=null;const setup=()=>prizes=Array.from({length:8},(_,i)=>({x:95+i*87,y:500,won:false,c:['#ff7bae','#ffd166','#6fe5a2','#5edcff'][i%4]}));return{reset(){x=400;y=90;mode='aim';held=null;setup()},move(d){begin();if(mode==='aim')x=clamp(x+(d==='left'?-38:d==='right'?38:0),55,745)},pointer(px,py,type){if(type==='move'&&mode==='aim'){begin();x=clamp(px,55,745)}if(type==='down')this.action()},action(){begin();if(mode==='aim'){mode='down';tone(300,.1)}},update(){if(mode==='aim'){if(keys.left)x-=5;if(keys.right)x+=5;x=clamp(x,55,745)}else if(mode==='down'){y+=7;if(y>440){held=prizes.find(p=>!p.won&&Math.abs(p.x-x)<38)||null;if(held&&Math.random()>.12){held.won=true;score+=25;ticket(5);tone(760,.18,'triangle')}mode='up'}}else if(mode==='up'){y-=7;if(held)held.y=y+45;if(y<=90){y=90;held=null;mode='aim';if(prizes.every(p=>p.won)){level++;ticket(20);setup();hud()}}}},draw(){bg('#24112d','#0c0714');rr(35,45,730,515,24,'rgba(255,255,255,.04)');ctx.fillStyle='#dfe8ff';ctx.fillRect(x-3,55,6,y-55);ctx.strokeStyle='#ffd166';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(x-24,y);ctx.lineTo(x,y+28);ctx.lineTo(x+24,y);ctx.stroke();prizes.forEach(p=>{if(p.won&&!held)return;rr(p.x-27,p.y-30,54,54,18,p.c);ctx.fillStyle='#10152a';ctx.font='28px system-ui';ctx.textAlign='center';ctx.fillText('★',p.x,p.y+7)})}}}
function bubble(){let bubbles,aim={x:400,y:160};const colors=['#ff6fae','#ffd166','#6fe5a2','#5edcff','#8c73ff'];const setup=()=>bubbles=Array.from({length:45},(_,i)=>({x:60+(i%9)*85,y:70+Math.floor(i/9)*55,r:24,c:colors[Math.floor(Math.random()*colors.length)],alive:true}));function popAt(x,y){begin();const b=bubbles.find(q=>q.alive&&Math.hypot(q.x-x,q.y-y)<q.r+12);if(!b){tone(140,.05,'square',.025);return}const same=bubbles.filter(q=>q.alive&&q.c===b.c&&Math.hypot(q.x-b.x,q.y-b.y)<105);if(same.length>=2){same.forEach(q=>q.alive=false);score+=same.length*10;tone(420+same.length*60,.12,'sine');hud();if(bubbles.every(q=>!q.alive)){level++;ticket(15);setup();hud()}}else tone(150,.08,'square')};return{reset(){setup()},pointer(x,y,type){aim={x,y};if(type==='down')popAt(x,y)},action(){const a=bubbles.find(q=>q.alive);if(a)popAt(a.x,a.y)},move(d){begin();aim.x=clamp(aim.x+(d==='left'?-45:d==='right'?45:0),40,760);if(d==='up')this.action()},update(){},draw(){bg('#19102d','#070a18');bubbles.forEach(b=>{if(!b.alive)return;ctx.shadowColor=b.c;ctx.shadowBlur=12;ctx.fillStyle=b.c;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(255,255,255,.45)';ctx.beginPath();ctx.arc(b.x-8,b.y-8,6,0,Math.PI*2);ctx.fill()});ctx.strokeStyle='#fff';ctx.globalAlpha=.45;ctx.beginPath();ctx.moveTo(400,570);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.globalAlpha=1}}}
function racer(){let lane,obs,spawnT,inv;const xs=[180,290,400,510,620];return{reset(){lane=2;obs=[];spawnT=0;inv=.8},respawn(){obs=obs.filter(o=>o.y<250);inv=1},move(d){begin();if(d==='left')lane=Math.max(0,lane-1);if(d==='right')lane=Math.min(4,lane+1);tone(250+lane*45,.05)},pointer(x){begin();lane=clamp(Math.round((x-180)/110),0,4)},action(){begin();const danger=new Set(obs.filter(o=>o.y>340).map(o=>o.l));for(let i=0;i<5;i++)if(!danger.has(i)){lane=i;tone(620,.08);break}},update(dt){inv=Math.max(0,inv-dt);spawnT+=dt;if(spawnT>.72){const l=Math.floor(Math.random()*5);obs.push({l,x:xs[l],y:-90,s:4+level*.35+Math.random()*2});spawnT=0}obs.forEach(o=>o.y+=o.s);obs=obs.filter(o=>{if(o.y>650){score++;hud();return false}return true});if(inv<=0&&obs.some(o=>Math.abs(o.x-xs[lane])<45&&o.y>475&&o.y<565)){inv=1;loseLife()}const next=1+Math.floor(score/25);if(next>level){level=next;ticket(5);hud()}},draw(){ctx.fillStyle='#16222d';ctx.fillRect(0,0,W,H);for(let i=0;i<5;i++){ctx.fillStyle=i%2?'#1d2d39':'#172832';ctx.fillRect(xs[i]-48,0,96,H);ctx.fillStyle='rgba(255,255,255,.22)';for(let y=0;y<H;y+=70)ctx.fillRect(xs[i]-3,y,6,38)}obs.forEach(o=>{rr(o.x-30,o.y,60,82,16,'#ff758f');rr(o.x-18,o.y+12,36,18,7,'#bcecff')});ctx.save();ctx.globalAlpha=inv>0&&Math.floor(inv*10)%2?0.4:1;rr(xs[lane]-32,500,64,86,18,'#5fe0ff');rr(xs[lane]-18,514,36,18,7,'#fff3b0');ctx.restore()}}}
function rhythm(){let seq,index,playing,flash,roundTimer;const freqs=[220,294,392,523],cols=['#ff6fae','#ffd166','#6fe5a2','#5edcff'];function clearRound(){clearInterval(roundTimer);roundTimer=null}function hitPad(i){begin();flash=i;tone(freqs[i],.18,'triangle',.08);setTimeout(()=>flash=-1,120);if(!playing)return;if(i===seq[index]){index++;score++;hud();if(index===seq.length){playing=false;ticket(4+seq.length);setTimeout(nextRound,500)}}else{index=0;tone(90,.2,'sawtooth')}}function nextRound(){clearRound();seq.push(Math.floor(Math.random()*4));index=0;playing=false;let n=0;roundTimer=setInterval(()=>{flash=seq[n];tone(freqs[seq[n]],.14,'sine');setTimeout(()=>flash=-1,150);n++;if(n>=seq.length){clearRound();playing=true}},430)}return{reset(){clearRound();seq=[];index=0;playing=false;flash=-1},move(d){hitPad(({up:0,left:1,right:2,down:3})[d]??0)},action(){begin();if(!seq.length||!playing)nextRound();else hitPad(0)},key(k){const i='1234'.indexOf(k);if(i>=0)hitPad(i)},pointer(x,y,type){if(type==='down')hitPad((x>400?1:0)+(y>300?2:0))},update(){},draw(){bg('#23112d','#090813');for(let i=0;i<4;i++){const x=i%2?420:90,y=i>1?330:90,w=290,h=190;rr(x,y,w,h,28,flash===i?'#fff':cols[i]);ctx.fillStyle='#09101d';ctx.font='900 42px system-ui';ctx.textAlign='center';ctx.fillText(i+1,x+w/2,y+112)}}}}
function blocks(){let p,bs,spawnT,inv;return{reset(){p={x:370,y:520,w:70,h:40};bs=[];spawnT=0;inv=.8},respawn(){bs=bs.filter(b=>b.y<300);inv=1},move(d){begin();p.x=clamp(p.x+(d==='left'?-64:d==='right'?64:0),0,730)},pointer(x){begin();p.x=clamp(x-35,0,730)},action(){begin();p.x=clamp(p.x+(p.x<W/2?125:-125),0,730);tone(500,.06)},update(dt){inv=Math.max(0,inv-dt);if(keys.left)p.x-=8;if(keys.right)p.x+=8;p.x=clamp(p.x,0,730);spawnT+=dt;if(spawnT>.44){bs.push({x:rand(0,730),y:-60,w:rand(35,105),h:rand(30,80),s:4+level*.35});spawnT=0}bs.forEach(b=>b.y+=b.s);bs=bs.filter(b=>{if(b.y>650){score++;hud();return false}return true});if(inv<=0&&bs.some(b=>hit(p,b))){inv=1;loseLife()}const next=1+Math.floor(score/25);if(next>level){level=next;ticket(5);hud()}},draw(){bg('#11162d','#060914');bs.forEach((b,i)=>rr(b.x,b.y,b.w,b.h,10,['#ff6f91','#ffd166','#8a72ff','#56e0ff'][i%4]));ctx.save();ctx.globalAlpha=inv>0&&Math.floor(inv*10)%2?0.4:1;rr(p.x,p.y,p.w,p.h,14,'#72eda8');ctx.restore()}}}
const makers={asteroids,claw,bubble,racer,rhythm,blocks};
function reset(){stopMusic();score=0;lives=3;level=1;tickets=0;running=false;paused=false;ended=false;keys={};game=(makers[id]||asteroids)();game.reset();ui.hint?.classList.remove('hide');hud()}
function togglePause(){if(ended)return;if(!running){begin();return}paused=!paused;if(paused)stopMusic();else startMusic();hud()}
function loop(t){const dt=Math.min(.04,(t-last)/1000||0);last=t;if(running&&!paused&&!ended)game.update(dt);game.draw();if(paused){ctx.fillStyle='rgba(3,7,15,.55)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 38px system-ui';ctx.fillText('Paused',W/2,H/2)}if(ended){ctx.fillStyle='rgba(3,7,15,.62)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 38px system-ui';ctx.fillText('Tap New Game',W/2,H/2)}requestAnimationFrame(loop)}
function setMove(d,on=true){keys[d]=on;if(on)game.move?.(d)}
$$('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();unlockAudio();setMove(b.dataset.move,true)});['pointerup','pointerleave','pointercancel'].forEach(n=>b.addEventListener(n,()=>setMove(b.dataset.move,false)))});
$('#actionBtn')?.addEventListener('click',()=>{unlockAudio();game.action?.()});
$('#pauseBtn')?.addEventListener('click',togglePause);
$('#resetBtn')?.addEventListener('click',reset);
$('#eyeBtn')?.addEventListener('click',()=>{eye=!eye;body.classList.toggle('eye-on',eye);$('#eyeBtn').textContent=eye?'Eye Control On':'Eye Control'});
$$('.control,.btn').forEach(el=>{el.addEventListener('pointerenter',()=>{if(!eye)return;clearTimeout(dwellTimer);el.classList.add('dwelling');dwellTimer=setTimeout(()=>{el.classList.remove('dwelling');el.click()},900)});el.addEventListener('pointerleave',()=>{clearTimeout(dwellTimer);el.classList.remove('dwelling')})});
D.addEventListener('keydown',e=>{const k=e.key.toLowerCase(),m={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'up',w:'up',arrowdown:'down',s:'down'}[k];if(m){e.preventDefault();unlockAudio();setMove(m,true)}if(k===' '||k==='enter'){e.preventDefault();unlockAudio();game.action?.()}if(k==='p')togglePause();if(k==='r')reset();game.key?.(k)},{passive:false});
D.addEventListener('keyup',e=>{const k=e.key.toLowerCase(),m={arrowleft:'left',a:'left',arrowright:'right',d:'right',arrowup:'up',w:'up',arrowdown:'down',s:'down'}[k];if(m)setMove(m,false)});
function point(e,type){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H;game.pointer?.(x,y,type)}
canvas.addEventListener('pointerdown',e=>{unlockAudio();point(e,'down')});canvas.addEventListener('pointermove',e=>point(e,'move'));canvas.addEventListener('pointerup',e=>point(e,'up'));canvas.addEventListener('contextmenu',e=>e.preventDefault());
D.addEventListener('visibilitychange',()=>{if(D.hidden&&running&&!paused){paused=true;stopMusic();hud()}});
window.addEventListener('blur',()=>{keys={}});
reset();requestAnimationFrame(loop);
})();