(()=>{
const W=800,H=600,TAU=Math.PI*2;
const TITLES={snake:'SNAKE',breakout:'BREAKOUT',invaders:'INVADERS',asteroids:'ASTEROIDS',pong:'PONG',claw:'CLAW MACHINE',bubble:'BUBBLE SHOOTER',memory:'MEMORY MATCH',racer:'MINI RACER',rhythm:'RHYTHM PADS',blocks:'FALLING BLOCKS',frog:'FROG DASH'};
const gameId=(document.body.dataset.game||window.RETROCADE_GAME||'snake').toLowerCase();
const title=TITLES[gameId]||gameId.toUpperCase();
const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d');
canvas.width=W;canvas.height=H;
const rand=(a,b)=>a+Math.random()*(b-a);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const state={running:false,paused:false,over:false,score:0,lives:3,level:1,t:0,last:0};
const keys={left:false,right:false,up:false,down:false,action:false,boost:false};
let game=null,pointer={x:0,y:0,down:false};
function show(a,b,type='',ms=750){if(window.RetroState)RetroState.show(a,b,type,ms)}
function win(t=1,x=1,c=0){if(window.retroWin)retroWin(t,x,c,gameId)}
function toast(t){if(window.retroToast)retroToast(t)}
function start(){if(state.over)reset();state.running=true;state.paused=false;show('GO','PLAY '+title,'',500);game?.start?.()}
function pause(){if(!state.running||state.over)return;state.paused=!state.paused;show(state.paused?'PAUSED':'GO',state.paused?'PRESS START':'PLAY','',500)}
function reset(){state.running=false;state.paused=false;state.over=false;state.score=0;state.lives=3;state.level=1;state.t=0;game=makeGame(gameId);game.reset();draw();show('READY','PRESS START','',650)}
function end(msg='GAME OVER'){state.running=false;state.over=true;show(msg,'RESET TO PLAY AGAIN','danger',1200);win(Math.floor(state.score/10),state.score,0)}
function clearScreen(){ctx.fillStyle='#05070c';ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(112,221,255,.07)';for(let y=0;y<H;y+=40)ctx.fillRect(0,y,W,1);for(let x=0;x<W;x+=40)ctx.fillRect(x,0,1,H)}
function hud(extra=''){ctx.fillStyle='#f6cf65';ctx.font='bold 20px system-ui';ctx.fillText('SCORE '+state.score,18,30);ctx.fillText('LIVES '+state.lives,650,30);if(extra)ctx.fillText(extra,340,30);if(!state.running&&!state.over){ctx.font='bold 44px system-ui';ctx.fillText('PRESS START',250,310)}if(state.paused){ctx.fillStyle='rgba(0,0,0,.56)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#f6cf65';ctx.font='bold 58px system-ui';ctx.fillText('PAUSED',295,315)}if(state.over){ctx.fillStyle='rgba(0,0,0,.58)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#ff75d8';ctx.font='bold 56px system-ui';ctx.fillText('GAME OVER',235,315)}}
function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill()}
function makeGame(id){return ({snake,breakout,invaders,asteroids,pong,claw,bubble,memory,racer,rhythm,blocks,frog}[id]||snake)()}
function snake(){let s,food,dir,next,acc;const cell=28,cols=24,rows=18,ox=64,oy=58;function spawn(){food={x:Math.floor(Math.random()*cols),y:Math.floor(Math.random()*rows)}}return{reset(){s=[{x:8,y:9},{x:7,y:9},{x:6,y:9}];dir={x:1,y:0};next={x:1,y:0};acc=0;spawn()},move(d){const m={left:{x:-1,y:0},right:{x:1,y:0},up:{x:0,y:-1},down:{x:0,y:1}}[d];if(m&&m.x+dir.x!==0&&m.y+dir.y!==0)next=m},update(dt){acc+=dt;if(acc<.105)return;acc=0;dir=next;const h={x:s[0].x+dir.x,y:s[0].y+dir.y};if(h.x<0||h.y<0||h.x>=cols||h.y>=rows||s.some(p=>p.x===h.x&&p.y===h.y)){end();return}s.unshift(h);if(h.x===food.x&&h.y===food.y){state.score+=10;win(2,4,0);spawn()}else s.pop()},draw(){clearScreen();ctx.strokeStyle='rgba(112,221,255,.18)';ctx.strokeRect(ox,oy,cols*cell,rows*cell);circle(ox+food.x*cell+cell/2,oy+food.y*cell+cell/2,10,'#ff75d8');s.forEach((p,i)=>{ctx.fillStyle=i?'#70ddff':'#86ff7b';ctx.fillRect(ox+p.x*cell+2,oy+p.y*cell+2,cell-4,cell-4)});hud('LENGTH '+s.length)}}}
function breakout(){let paddle,ball,bricks;function wall(){bricks=[];for(let y=0;y<5;y++)for(let x=0;x<10;x++)bricks.push({x:70+x*66,y:70+y*28,w:56,h:18,c:['#70ddff','#ff75d8','#f6cf65','#86ff7b','#ffc86a'][y]})}return{reset(){paddle=330;ball={x:400,y:430,vx:4,vy:-5};state.lives=3;wall()},pointer(x){paddle=clamp(x-60,20,660)},update(){if(keys.left)paddle-=7;if(keys.right)paddle+=7;paddle=clamp(paddle,20,660);ball.x+=ball.vx;ball.y+=ball.vy;if(ball.x<12||ball.x>788)ball.vx*=-1;if(ball.y<12)ball.vy*=-1;if(ball.y>600){state.lives--;if(state.lives<=0)end();ball={x:paddle+60,y:430,vx:4,vy:-5}}if(ball.y>505&&ball.y<525&&ball.x>paddle&&ball.x<paddle+120){ball.vy=-Math.abs(ball.vy);ball.vx=(ball.x-(paddle+60))*.09}bricks=bricks.filter(b=>{if(ball.x>b.x&&ball.x<b.x+b.w&&ball.y>b.y&&ball.y<b.y+b.h){ball.vy*=-1;state.score+=10;win(1,2,0);return false}return true});if(!bricks.length){state.level++;state.score+=100;win(20,40,5);wall()}},draw(){clearScreen();bricks.forEach(b=>{ctx.fillStyle=b.c;ctx.fillRect(b.x,b.y,b.w,b.h)});ctx.fillStyle='#70ddff';ctx.fillRect(paddle,520,120,16);circle(ball.x,ball.y,10,'#f6cf65');hud('LEVEL '+state.level)}}}
function invaders(){let px,shots,enemyShots,enemies,dir,fireCd;function wave(){enemies=[];for(let y=0;y<4;y++)for(let x=0;x<9;x++)enemies.push({x:92+x*64,y:70+y*42,w:34,h:24})}return{reset(){px=370;shots=[];enemyShots=[];dir=1;fireCd=0;state.lives=3;wave()},action(){if(fireCd<=0){shots.push({x:px+28,y:500,w:5,h:15});fireCd=.18}},update(dt){fireCd-=dt;if(keys.left)px-=7;if(keys.right)px+=7;px=clamp(px,20,720);shots.forEach(s=>s.y-=10);enemyShots.forEach(s=>s.y+=5);let edge=false;enemies.forEach(e=>{e.x+=dir*(1+state.level*.15);if(e.x<20||e.x>745)edge=true});if(edge){dir*=-1;enemies.forEach(e=>e.y+=18)}if(Math.random()<.02&&enemies.length){const e=enemies[Math.floor(Math.random()*enemies.length)];enemyShots.push({x:e.x+15,y:e.y+20,w:5,h:14})}shots=shots.filter(s=>s.y>-20);enemyShots=enemyShots.filter(s=>s.y<620);enemies=enemies.filter(e=>{const h=shots.find(s=>hit(s,e));if(h){h.dead=true;state.score+=10;win(2,4,0);return false}return true});shots=shots.filter(s=>!s.dead);if(enemyShots.some(s=>hit(s,{x:px,y:505,w:60,h:18}))||enemies.some(e=>e.y>485)){state.lives--;enemyShots=[];if(state.lives<=0)end()}if(!enemies.length){state.level++;state.score+=100;win(25,50,5);wave()}},draw(){clearScreen();ctx.fillStyle='#70ddff';ctx.fillRect(px,505,60,18);shots.forEach(s=>{ctx.fillStyle='#f6cf65';ctx.fillRect(s.x,s.y,s.w,s.h)});enemyShots.forEach(s=>{ctx.fillStyle='#ff5757';ctx.fillRect(s.x,s.y,s.w,s.h)});enemies.forEach(e=>{ctx.fillStyle='#ff75d8';ctx.fillRect(e.x,e.y,e.w,e.h)});hud('WAVE '+state.level)}}}
function asteroids(){let ship,rocks,shots,fireCd;function rock(){return{x:rand(40,760),y:rand(50,550),vx:rand(-2,2),vy:rand(-2,2),r:rand(18,38)}}function spawn(){rocks=Array.from({length:5+state.level},rock)}return{reset(){ship={x:400,y:300,a:-Math.PI/2,vx:0,vy:0};shots=[];fireCd=0;state.lives=3;spawn()},action(){if(fireCd<=0){shots.push({x:ship.x,y:ship.y,vx:Math.cos(ship.a)*8,vy:Math.sin(ship.a)*8,life:70});fireCd=.16}},update(dt){fireCd-=dt;if(keys.left)ship.a-=.08;if(keys.right)ship.a+=.08;if(keys.up){ship.vx+=Math.cos(ship.a)*.18;ship.vy+=Math.sin(ship.a)*.18}ship.x=(ship.x+ship.vx+W)%W;ship.y=(ship.y+ship.vy+H)%H;ship.vx*=.99;ship.vy*=.99;shots.forEach(s=>{s.x=(s.x+s.vx+W)%W;s.y=(s.y+s.vy+H)%H;s.life--});shots=shots.filter(s=>s.life>0);rocks.forEach(r=>{r.x=(r.x+r.vx+W)%W;r.y=(r.y+r.vy+H)%H});rocks=rocks.filter(r=>{const h=shots.find(s=>Math.hypot(s.x-r.x,s.y-r.y)<r.r);if(h){h.life=0;state.score+=15;win(2,4,0);return false}return true});if(rocks.some(r=>Math.hypot(ship.x-r.x,ship.y-r.y)<r.r+14)){state.lives--;ship.x=400;ship.y=300;if(state.lives<=0)end()}if(!rocks.length){state.level++;state.score+=100;win(25,50,5);spawn()}},draw(){clearScreen();rocks.forEach(r=>{ctx.strokeStyle='#ff75d8';ctx.lineWidth=3;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,TAU);ctx.stroke()});shots.forEach(s=>circle(s.x,s.y,3,'#f6cf65'));ctx.save();ctx.translate(ship.x,ship.y);ctx.rotate(ship.a);ctx.strokeStyle='#70ddff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(18,0);ctx.lineTo(-14,-10);ctx.lineTo(-8,0);ctx.lineTo(-14,10);ctx.closePath();ctx.stroke();ctx.restore();hud('WAVE '+state.level)}}}
function pong(){let py,ay,ball,ls,rs;return{reset(){py=240;ay=240;ls=0;rs=0;ball={x:400,y:300,vx:5,vy:3}},pointer(x,y){py=clamp(y-50,20,480)},update(){if(keys.up)py-=7;if(keys.down)py+=7;py=clamp(py,20,480);ay+=clamp(ball.y-(ay+50),-5,5);ay=clamp(ay,20,480);ball.x+=ball.vx;ball.y+=ball.vy;if(ball.y<10||ball.y>590)ball.vy*=-1;if(ball.x<45&&ball.y>ay&&ball.y<ay+100)ball.vx=Math.abs(ball.vx);if(ball.x>740&&ball.y>py&&ball.y<py+100)ball.vx=-Math.abs(ball.vx);if(ball.x<0){rs++;ball.x=400;ball.vx=5}if(ball.x>800){ls++;state.score+=10;win(2,3,0);ball.x=400;ball.vx=-5}},draw(){clearScreen();ctx.fillStyle='#ff75d8';ctx.fillRect(25,ay,14,100);ctx.fillStyle='#70ddff';ctx.fillRect(760,py,14,100);circle(ball.x,ball.y,9,'#f6cf65');ctx.fillStyle='#fff';ctx.font='bold 34px system-ui';ctx.fillText(ls,330,50);ctx.fillText(rs,455,50);hud()}}}
function claw(){let x,y,mode,prizes,grab;function prizeset(){prizes=Array.from({length:8},(_,i)=>({x:105+i*82,y:500,r:18,c:['#70ddff','#ff75d8','#f6cf65','#86ff7b'][i%4],won:false}))}return{reset(){x=400;y=90;mode='aim';grab=null;prizeset()},action(){if(mode==='aim'){mode='down'}},update(){if(mode==='aim'){if(keys.left)x-=5;if(keys.right)x+=5;x=clamp(x,50,750)}if(mode==='down'){y+=7;if(y>440){const p=prizes.find(p=>!p.won&&Math.abs(p.x-x)<35);if(p&&Math.random()>.15){p.won=true;grab=p;state.score++;win(20,30,2)}mode='up'}}if(mode==='up'){y-=7;if(y<=90){y=90;grab=null;mode='aim';if(prizes.every(p=>p.won)){state.score+=100;win(80,100,10);prizeset()}}}},draw(){clearScreen();ctx.strokeStyle='#70ddff';ctx.strokeRect(40,50,720,500);ctx.strokeStyle='#f6cf65';ctx.beginPath();ctx.moveTo(x,60);ctx.lineTo(x,y);ctx.stroke();ctx.strokeRect(x-22,y,44,24);prizes.forEach(p=>{if(!p.won)circle(p.x,p.y,p.r,p.c)});if(grab)circle(x,y+42,grab.r,grab.c);hud('PRIZES '+state.score)}}}
function bubble(){let bubs,colors=['#70ddff','#ff75d8','#f6cf65','#86ff7b'];function setup(){bubs=[];for(let y=0;y<8;y++)for(let x=0;x<10;x++)bubs.push({x:112+x*60+(y%2?30:0),y:80+y*55,c:colors[Math.floor(Math.random()*4)]})}function cluster(start){const open=[start],seen=new Set([start]);while(open.length){const p=open.pop();bubs.forEach(n=>{if(!seen.has(n)&&n.c===p.c&&Math.hypot(n.x-p.x,n.y-p.y)<64){seen.add(n);open.push(n)}})}return[...seen]}return{reset:setup,pointer(x,y,type){if(type!=='down')return;const h=bubs.find(b=>Math.hypot(x-b.x,y-b.y)<25);if(!h)return;const cl=cluster(h);if(cl.length<2)return show('NO MATCH','TRY A GROUP','',450);bubs=bubs.filter(b=>!cl.includes(b));state.score+=cl.length;win(cl.length,cl.length*2,Math.floor(cl.length/4));if(!bubs.length){state.score+=100;setup()}},update(){},draw(){clearScreen();bubs.forEach(b=>circle(b.x,b.y,23,b.c));hud('LEFT '+bubs.length)}}}
function memory(){let cards,open,matched,icons=['★','◆','●','▲','☀','☾','♬','☕'];function setup(){cards=[...icons,...icons].sort(()=>Math.random()-.5).map((v,i)=>({v,i}));open=[];matched=new Set()}function flip(i){if(matched.has(i)||open.includes(i))return;open.push(i);if(open.length===2){const[a,b]=open;if(cards[a].v===cards[b].v){matched.add(a);matched.add(b);state.score+=10;win(5,8,1);open=[];if(matched.size===cards.length){state.score+=100;win(50,80,8);setup()}}else setTimeout(()=>{open=[]},500)}}return{reset:setup,pointer(x,y,type){if(type!=='down')return;const cw=120,ch=90,gap=16,ox=136,oy=88;const cx=Math.floor((x-ox)/(cw+gap)),cy=Math.floor((y-oy)/(ch+gap));if(cx>=0&&cx<4&&cy>=0&&cy<4)flip(cy*4+cx)},action(){const i=cards.findIndex((_,i)=>!matched.has(i)&&!open.includes(i));if(i>=0)flip(i)},update(){},draw(){clearScreen();const cw=120,ch=90,gap=16,ox=136,oy=88;cards.forEach((card,i)=>{const x=ox+(i%4)*(cw+gap),y=oy+Math.floor(i/4)*(ch+gap);const show=open.includes(i)||matched.has(i);ctx.fillStyle=show?'#70ddff':'#263955';ctx.fillRect(x,y,cw,ch);ctx.strokeStyle='#fff';ctx.strokeRect(x,y,cw,ch);ctx.fillStyle=show?'#101827':'#f6cf65';ctx.font='bold 38px system-ui';ctx.fillText(show?card.v:'?',x+48,y+56)});hud('MATCH '+(matched.size/2))}}}
function racer(){let lane,obs,spawnT,lanes=[170,270,370,470,570];function spawn(){const l=Math.floor(Math.random()*lanes.length);obs.push({lane:l,x:lanes[l],y:-90,w:54,h:80,c:['#ff75d8','#70ddff','#f6cf65'][Math.floor(Math.random()*3)]})}return{reset(){lane=2;obs=[];spawnT=0;state.lives=1},move(d){if(d==='left')lane=clamp(lane-1,0,4);if(d==='right')lane=clamp(lane+1,0,4)},update(dt){spawnT+=dt;if(spawnT>.7){spawn();spawnT=0}obs.forEach(o=>o.y+=5+state.score/80);obs=obs.filter(o=>{if(o.y>650){state.score++;return false}return true});if(obs.some(o=>hit({x:lanes[lane]-27,y:500,w:54,h:80},o)))end('CRASH')},draw(){clearScreen();ctx.fillStyle='#1b2230';ctx.fillRect(120,0,560,H);for(let x of lanes){ctx.fillStyle='rgba(255,255,255,.18)';ctx.fillRect(x,0,4,H)}obs.forEach(o=>{ctx.fillStyle=o.c;ctx.fillRect(o.x-27,o.y,o.w,o.h)});ctx.fillStyle='#86ff7b';ctx.fillRect(lanes[lane]-27,500,54,80);hud('LANE '+(lane+1))}}}
function rhythm(){let pads=[220,330,440,550],last=-1,audio=null;function beep(i){last=i;state.score++;win(1,1,0);try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume&&audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=pads[i];o.type='square';o.connect(g);g.connect(audio.destination);g.gain.value=.08;o.start();g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.18);o.stop(audio.currentTime+.2)}catch(e){}}return{reset(){last=-1},pointer(x,y,type){if(type!=='down')return;const i=(x<400?0:1)+(y>300?2:0);beep(i)},action(){beep(Math.floor(Math.random()*4))},key(k){const i='1234'.indexOf(k);if(i>=0)beep(i)},update(){},draw(){clearScreen();for(let i=0;i<4;i++){const x=i%2?430:170,y=i>1?340:130;ctx.fillStyle=i===last?'#f6cf65':['#70ddff','#ff75d8','#86ff7b','#ffc86a'][i];ctx.fillRect(x,y,200,150);ctx.fillStyle='#101827';ctx.font='bold 32px system-ui';ctx.fillText('PAD '+(i+1),x+52,y+88)}hud('TAPS '+state.score)}}}
function blocks(){let p,bs,spawnT;function spawn(){bs.push({x:rand(0,740),y:-50,w:rand(35,95),h:rand(25,65),c:['#70ddff','#ff75d8','#f6cf65'][Math.floor(Math.random()*3)]})}return{reset(){p={x:370,y:520,w:60,h:40};bs=[];spawnT=0},pointer(x){p.x=clamp(x-30,0,740)},update(dt){if(keys.left)p.x-=8;if(keys.right)p.x+=8;p.x=clamp(p.x,0,740);spawnT+=dt;if(spawnT>.45){spawn();spawnT=0}bs.forEach(b=>b.y+=4+state.score/90);bs=bs.filter(b=>{if(b.y>640){state.score++;return false}return true});if(bs.some(b=>hit(p,b)))end('BLOCKED')},draw(){clearScreen();bs.forEach(b=>{ctx.fillStyle=b.c;ctx.fillRect(b.x,b.y,b.w,b.h)});ctx.fillStyle='#86ff7b';ctx.fillRect(p.x,p.y,p.w,p.h);hud()}}}
function frog(){let f,cars,spawnT,cross;function spawn(){const lanes=[120,180,240,300,360,420,480];const y=lanes[Math.floor(Math.random()*lanes.length)],left=Math.random()>.5;cars.push({x:left?-100:850,y,w:80,h:34,v:(left?1:-1)*rand(2.5,5.5),c:['#70ddff','#ff75d8','#f6cf65'][Math.floor(Math.random()*3)]})}return{reset(){f={x:380,y:540,w:36,h:36,inv:.8};cars=[];spawnT=0;cross=0},move(d){if(d==='left')f.x-=40;if(d==='right')f.x+=40;if(d==='up')f.y-=40;if(d==='down')f.y+=40;f.x=clamp(f.x,0,764);f.y=clamp(f.y,20,550);if(f.y<=30){cross++;state.score+=10;win(8,14,1);f.x=380;f.y=540;f.inv=.8}},update(dt){if(f.inv>0)f.inv-=dt;spawnT+=dt;if(spawnT>.45){spawn();spawnT=0}cars.forEach(c=>c.x+=c.v);cars=cars.filter(c=>c.x>-150&&c.x<950);if(f.inv<=0&&cars.some(c=>hit(f,c)))end('SPLAT')},draw(){clearScreen();ctx.fillStyle='rgba(134,255,123,.16)';ctx.fillRect(0,0,W,70);ctx.fillRect(0,530,W,70);cars.forEach(c=>{ctx.fillStyle=c.c;ctx.fillRect(c.x,c.y,c.w,c.h)});ctx.globalAlpha=f.inv>0?.55:1;ctx.fillStyle='#86ff7b';ctx.fillRect(f.x,f.y,f.w,f.h);ctx.globalAlpha=1;hud('CROSS '+cross)}}}
function update(dt){if(state.running&&!state.paused&&!state.over)game.update(dt)}
function draw(){game.draw()}
function loop(ts){const dt=Math.min(.05,(ts-(state.last||ts))/1000);state.last=ts;state.t+=dt;update(dt);draw();requestAnimationFrame(loop)}
function bind(){const by=id=>document.getElementById(id);['startBtn','touchStart'].forEach(id=>by(id)?.addEventListener('click',start));['pauseBtn','touchPause'].forEach(id=>by(id)?.addEventListener('click',pause));['resetBtn','touchReset'].forEach(id=>by(id)?.addEventListener('click',reset));['actionBtn','fireBtn','dropBtn','hopBtn','dashBtn','boostBtn'].forEach(id=>by(id)?.addEventListener('click',()=>{if(!state.running)start();game.action?.()}));document.querySelectorAll('[data-move]').forEach(btn=>{btn.addEventListener('pointerdown',()=>{if(!state.running)start();const d=btn.dataset.move;keys[d]=true;game.move?.(d)});btn.addEventListener('pointerup',()=>keys[btn.dataset.move]=false);btn.addEventListener('pointerleave',()=>keys[btn.dataset.move]=false);btn.addEventListener('pointercancel',()=>keys[btn.dataset.move]=false)});canvas.addEventListener('pointerdown',e=>{if(!state.running)start();pointer.down=true;point(e,'down')});canvas.addEventListener('pointermove',e=>point(e,'move'));canvas.addEventListener('pointerup',e=>{pointer.down=false;point(e,'up')});document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a'){keys.left=true;game.move?.('left')}if(k==='arrowright'||k==='d'){keys.right=true;game.move?.('right')}if(k==='arrowup'||k==='w'){keys.up=true;game.move?.('up')}if(k==='arrowdown'||k==='s'){keys.down=true;game.move?.('down')}if(k===' '||k==='enter'){if(!state.running)start();else game.action?.()}if(k==='p')pause();if(k==='r')reset();if(k==='shift')keys.boost=true;game.key?.(k)});document.addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a')keys.left=false;if(k==='arrowright'||k==='d')keys.right=false;if(k==='arrowup'||k==='w')keys.up=false;if(k==='arrowdown'||k==='s')keys.down=false;if(k==='shift')keys.boost=false})}
function point(e,type){const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*W;pointer.y=(e.clientY-r.top)/r.height*H;game.pointer?.(pointer.x,pointer.y,type)}
reset();bind();requestAnimationFrame(loop);
})();
